# -*- coding: utf-8 -*-
"""Berlin_get_labels.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VKlWEnpwbszw9ocv8KqdzU2b5ipFejTW
"""

import pickle 
import geopy
from geopy.geocoders import Nominatim
import numpy as np 

classifier = pickle.load(open("knn_model.sav", 'rb'))

def getLatAndLong(place):
  geolocator = Nominatim()
  location = geolocator.geocode(place)
  return location.latitude, location.longitude

#function to make a prediction on a single value: 
def predictPlace(place, classifier):
  #get the lat and long 
  lat, long = getLatAndLong(place)
  coord = np.array([lat,long])
  coord = coord.reshape(1,-1)

  pred = classifier.predict(coord)

  return pred[0]

predictPlace("Reichstag", classifier)